import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";

const root = process.cwd();

test("web exposes image detail workflow from history and favorites", async () => {
  const detailPage = await readFile(join(root, "apps/web/app/images/[imageId]/page.tsx"), "utf8");
  const historyPage = await readFile(join(root, "apps/web/app/history/page.tsx"), "utf8");
  const favoritesPage = await readFile(join(root, "apps/web/app/favorites/page.tsx"), "utf8");

  assert.match(detailPage, /\/api\/images\/\$\{imageId\}/);
  assert.match(detailPage, /\/api\/generation\/tasks\/\$\{(?:image|imageResult\.image)\.taskId\}/);
  assert.match(detailPage, /download-url/);
  assert.match(detailPage, /favorite/);
  assert.match(detailPage, /再次生成/);
  assert.match(detailPage, /删除图片/);
  assert.match(historyPage, /href=\{`\/images\/\$\{image\.id\}`\}/);
  assert.match(favoritesPage, /href=\{`\/images\/\$\{image\.id\}`\}/);
});

test("web auth pages validate inputs and registration does not ask for nickname", async () => {
  const apiClient = await readFile(join(root, "apps/web/lib/api.ts"), "utf8");
  const apiMain = await readFile(join(root, "apps/api/src/main.ts"), "utf8");
  const appFrame = await readFile(join(root, "apps/web/components/AppFrame.tsx"), "utf8");
  const forgotPasswordPage = await readFile(join(root, "apps/web/app/forgot-password/page.tsx"), "utf8");
  const loginPage = await readFile(join(root, "apps/web/app/login/page.tsx"), "utf8");
  const nextConfig = await readFile(join(root, "apps/web/next.config.mjs"), "utf8");
  const registerPage = await readFile(join(root, "apps/web/app/register/page.tsx"), "utf8");
  const resetPasswordPage = await readFile(join(root, "apps/web/app/reset-password/page.tsx"), "utf8");
  const verifyEmailPage = await readFile(join(root, "apps/web/app/verify-email/page.tsx"), "utf8");

  assert.match(appFrame, /role="dialog"/);
  assert.match(appFrame, /确认退出/);
  assert.match(appFrame, /await apiLogout/);
  assert.match(appFrame, /autoFocus/);
  assert.match(loginPage, /validateLoginForm/);
  assert.match(loginPage, /role="alert"/);
  assert.match(loginPage, /captchaSelections/);
  assert.match(loginPage, /captchaVerificationIds/);
  assert.match(loginPage, /requiredCaptchaRounds = 2/);
  assert.match(loginPage, /verifyLoginCaptcha/);
  assert.match(loginPage, /handleCaptchaClick/);
  assert.match(loginPage, /已选择/);
  assert.match(loginPage, /aspect-\[18\/13\]/);
  assert.match(loginPage, /acceptLoginRules/);
  assert.match(loginPage, /captchaPanelOpen/);
  assert.match(loginPage, /点击文字进行图片验证/);
  assert.match(loginPage, /我已阅读并同意登录安全准则/);
  assert.match(loginPage, /role="dialog"/);
  assert.match(loginPage, /data:image\/svg\+xml;utf8/);
  assert.doesNotMatch(loginPage, /dangerouslySetInnerHTML/);
  assert.match(registerPage, /validateRegisterForm/);
  assert.match(registerPage, /confirmPassword/);
  assert.match(registerPage, /onPaste=\{handleConfirmPasswordPaste\}/);
  assert.match(registerPage, /event\.preventDefault\(\)/);
  assert.match(registerPage, /role="alert"/);
  assert.match(registerPage, /commonPasswordBlocklist/);
  assert.doesNotMatch(registerPage, /昵称/);
  assert.doesNotMatch(registerPage, /nickname/);
  assert.match(resetPasswordPage, /validateResetPasswordForm/);
  assert.match(resetPasswordPage, /密码至少需要 12 位/);
  assert.match(resetPasswordPage, /role=\{success \? "status" : "alert"\}/);
  assert.match(forgotPasswordPage, /validateForgotPasswordForm/);
  assert.match(forgotPasswordPage, /role=\{success \? "status" : "alert"\}/);
  assert.match(verifyEmailPage, /role="status"/);
  assert.match(apiClient, /AbortController/);
  assert.match(apiClient, /verifyLoginCaptcha/);
  assert.match(apiClient, /captchaVerificationIds/);
  assert.match(apiClient, /captchaSelections/);
  assert.match(apiClient, /请求超时，请检查网络后重试。/);
  assert.match(apiClient, /INVALID_RESET_TOKEN/);
  assert.match(apiMain, /password: newPasswordSchema/);
  assert.match(apiMain, /captchaVerifications/);
  assert.match(apiMain, /captchaRequiredRounds/);
  assert.match(apiMain, /captchaSelections/);
  assert.match(apiMain, /createCaptchaChallenge/);
  assert.match(nextConfig, /X-Content-Type-Options/);
  assert.match(nextConfig, /X-Frame-Options/);
  assert.match(nextConfig, /Permissions-Policy/);
});
